import { CardiacRhythm } from '../../types/rhythms';
import type { RhythmDefinition } from '../../types/rhythms';

export const RHYTHM_DEFINITIONS: Record<CardiacRhythm, RhythmDefinition> = {
  // === SINUS RHYTHMS ===
  [CardiacRhythm.NORMAL_SINUS]: {
    id: CardiacRhythm.NORMAL_SINUS,
    name: "Normal Sinus Rhythm",
    nameEs: "Ritmo Sinusal Normal",
    category: "sinus",
    defaultHR: 71,
    hrRange: [60, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 119, diastolicBP: 81, spo2: 97, etco2: 34, respiratoryRate: 17, temperature: 36.4 },
  },

  [CardiacRhythm.SINUS_BRADYCARDIA]: {
    id: CardiacRhythm.SINUS_BRADYCARDIA,
    name: "Sinus Bradycardia",
    nameEs: "Bradicardia Sinusal",
    category: "sinus",
    defaultHR: 49,
    hrRange: [30, 59],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 180,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.25, width: 0.065, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 99, diastolicBP: 64, spo2: 95, etco2: 37, respiratoryRate: 13, temperature: 36.4 },
  },

  [CardiacRhythm.SINUS_TACHYCARDIA]: {
    id: CardiacRhythm.SINUS_TACHYCARDIA,
    name: "Sinus Tachycardia",
    nameEs: "Taquicardia Sinusal",
    category: "sinus",
    defaultHR: 119,
    hrRange: [101, 150],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.12, width: 0.03, present: true },
      prInterval: 140,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.75, width: 0.016 },
      sWave: { amplitude: 0.1, width: 0.011 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.18, width: 0.05, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 139, diastolicBP: 84, spo2: 96, etco2: 31, respiratoryRate: 23, temperature: 37.3 },
  },

  [CardiacRhythm.SINUS_ARRHYTHMIA]: {
    id: CardiacRhythm.SINUS_ARRHYTHMIA,
    name: "Sinus Arrhythmia",
    nameEs: "Arritmia Sinusal",
    category: "sinus",
    defaultHR: 73,
    hrRange: [55, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0.25,
      baselineWander: 0.015,
    },
    physiologicalDefaults: { systolicBP: 119, diastolicBP: 81, spo2: 97, etco2: 34, respiratoryRate: 17, temperature: 36.6 },
  },

  [CardiacRhythm.SINUS_EXIT_BLOCK]: {
    id: CardiacRhythm.SINUS_EXIT_BLOCK,
    name: "Sinus Exit Block",
    nameEs: "Bloqueo de Salida Sinusal",
    category: "sinus",
    defaultHR: 61,
    hrRange: [40, 80],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0.15,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 109, diastolicBP: 71, spo2: 98, etco2: 37, respiratoryRate: 16, temperature: 36.6 },
  },

  // === SUPRAVENTRICULAR ===
  [CardiacRhythm.SVT]: {
    id: CardiacRhythm.SVT,
    name: "Supraventricular Tachycardia",
    nameEs: "Taquicardia Supraventricular",
    category: "supraventricular",
    defaultHR: 179,
    hrRange: [150, 250],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 80,
      qWave: { amplitude: 0.06, width: 0.01 },
      rWave: { amplitude: 0.7, width: 0.015 },
      sWave: { amplitude: 0.08, width: 0.01 },
      stSegment: { elevation: -0.05 },
      tWave: { amplitude: 0.1, width: 0.04, inverted: false },
      irregularity: 0,
      baselineWander: 0.005,
    },
    physiologicalDefaults: { systolicBP: 99, diastolicBP: 69, spo2: 97, etco2: 27, respiratoryRate: 25, temperature: 36.9 },
  },

  [CardiacRhythm.PEDIATRIC_SVT]: {
    id: CardiacRhythm.PEDIATRIC_SVT,
    name: "Pediatric SVT",
    nameEs: "TSV Pediátrica",
    category: "supraventricular",
    defaultHR: 241,
    hrRange: [220, 300],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 70,
      qWave: { amplitude: 0.04, width: 0.008 },
      rWave: { amplitude: 0.6, width: 0.012 },
      sWave: { amplitude: 0.06, width: 0.008 },
      stSegment: { elevation: -0.03 },
      tWave: { amplitude: 0.08, width: 0.03, inverted: false },
      irregularity: 0,
      baselineWander: 0.005,
    },
    physiologicalDefaults: { systolicBP: 79, diastolicBP: 51, spo2: 94, etco2: 26, respiratoryRate: 31, temperature: 36.9 },
  },

  [CardiacRhythm.ATRIAL_FIBRILLATION]: {
    id: CardiacRhythm.ATRIAL_FIBRILLATION,
    name: "Atrial Fibrillation",
    nameEs: "Fibrilación Auricular",
    category: "supraventricular",
    defaultHR: 109,
    hrRange: [60, 180],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.75, width: 0.017 },
      sWave: { amplitude: 0.1, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.18, width: 0.055, inverted: false },
      irregularity: 0.6,
      baselineWander: 0.02,
    },
    physiologicalDefaults: { systolicBP: 116, diastolicBP: 74, spo2: 95, etco2: 34, respiratoryRate: 17, temperature: 36.7 },
  },

  [CardiacRhythm.ATRIAL_FLUTTER]: {
    id: CardiacRhythm.ATRIAL_FLUTTER,
    name: "Atrial Flutter",
    nameEs: "Flutter Auricular",
    category: "supraventricular",
    defaultHR: 151,
    hrRange: [75, 300],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 80,
      qWave: { amplitude: 0.07, width: 0.011 },
      rWave: { amplitude: 0.7, width: 0.016 },
      sWave: { amplitude: 0.09, width: 0.011 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.12, width: 0.04, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 109, diastolicBP: 69, spo2: 97, etco2: 33, respiratoryRate: 21, temperature: 36.6 },
  },

  [CardiacRhythm.WANDERING_ATRIAL_PACEMAKER]: {
    id: CardiacRhythm.WANDERING_ATRIAL_PACEMAKER,
    name: "Wandering Atrial Pacemaker",
    nameEs: "Marcapasos Auricular Errante",
    category: "supraventricular",
    defaultHR: 64,
    hrRange: [50, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.12, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0.2,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 117, diastolicBP: 79, spo2: 98, etco2: 36, respiratoryRate: 17, temperature: 36.4 },
  },

  [CardiacRhythm.MULTIFOCAL_ATRIAL_TACHYCARDIA]: {
    id: CardiacRhythm.MULTIFOCAL_ATRIAL_TACHYCARDIA,
    name: "Multifocal Atrial Tachycardia",
    nameEs: "Taquicardia Auricular Multifocal",
    category: "supraventricular",
    defaultHR: 129,
    hrRange: [100, 180],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.12, width: 0.03, present: true },
      prInterval: 150,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.75, width: 0.017 },
      sWave: { amplitude: 0.1, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.18, width: 0.05, inverted: false },
      irregularity: 0.4,
      baselineWander: 0.015,
    },
    physiologicalDefaults: { systolicBP: 124, diastolicBP: 79, spo2: 93, etco2: 31, respiratoryRate: 23, temperature: 36.9 },
  },

  // === AV BLOCKS ===
  [CardiacRhythm.FIRST_DEGREE_AV_BLOCK]: {
    id: CardiacRhythm.FIRST_DEGREE_AV_BLOCK,
    name: "First Degree AV Block",
    nameEs: "BAV 1er Grado",
    category: "av_block",
    defaultHR: 67,
    hrRange: [50, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 240,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 119, diastolicBP: 75, spo2: 96, etco2: 36, respiratoryRate: 15, temperature: 36.6 },
  },

  [CardiacRhythm.SECOND_DEGREE_TYPE_1]: {
    id: CardiacRhythm.SECOND_DEGREE_TYPE_1,
    name: "Second Degree Type I (Wenckebach)",
    nameEs: "BAV 2do Grado Tipo I (Wenckebach)",
    category: "av_block",
    defaultHR: 59,
    hrRange: [40, 80],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 200,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0.3,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 109, diastolicBP: 69, spo2: 95, etco2: 37, respiratoryRate: 16, temperature: 36.6 },
  },

  [CardiacRhythm.SECOND_DEGREE_TYPE_2]: {
    id: CardiacRhythm.SECOND_DEGREE_TYPE_2,
    name: "Second Degree Type II",
    nameEs: "BAV 2do Grado Tipo II",
    category: "av_block",
    defaultHR: 54,
    hrRange: [30, 70],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 200,
      qrsWidth: 120,
      qWave: { amplitude: 0.08, width: 0.015 },
      rWave: { amplitude: 0.8, width: 0.022 },
      sWave: { amplitude: 0.15, width: 0.015 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0.2,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 106, diastolicBP: 64, spo2: 94, etco2: 35, respiratoryRate: 13, temperature: 36.3 },
  },

  [CardiacRhythm.THIRD_DEGREE_AV_BLOCK]: {
    id: CardiacRhythm.THIRD_DEGREE_AV_BLOCK,
    name: "Third Degree AV Block",
    nameEs: "BAV 3er Grado (Completo)",
    category: "av_block",
    defaultHR: 39,
    hrRange: [25, 50],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 0,
      qrsWidth: 140,
      qWave: { amplitude: 0.1, width: 0.018 },
      rWave: { amplitude: 0.7, width: 0.025 },
      sWave: { amplitude: 0.15, width: 0.018 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.25, width: 0.07, inverted: true },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 91, diastolicBP: 61, spo2: 93, etco2: 39, respiratoryRate: 15, temperature: 36.4 },
  },

  // === JUNCTIONAL ===
  [CardiacRhythm.JUNCTIONAL_RHYTHM]: {
    id: CardiacRhythm.JUNCTIONAL_RHYTHM,
    name: "Junctional Rhythm",
    nameEs: "Ritmo de la Unión",
    category: "junctional",
    defaultHR: 51,
    hrRange: [40, 60],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: -0.08, width: 0.025, present: true },
      prInterval: 100,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 104, diastolicBP: 67, spo2: 95, etco2: 37, respiratoryRate: 14, temperature: 36.6 },
  },

  [CardiacRhythm.JUNCTIONAL_TACHYCARDIA]: {
    id: CardiacRhythm.JUNCTIONAL_TACHYCARDIA,
    name: "Junctional Tachycardia",
    nameEs: "Taquicardia de la Unión",
    category: "junctional",
    defaultHR: 111,
    hrRange: [60, 150],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: -0.06, width: 0.02, present: true },
      prInterval: 80,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.75, width: 0.017 },
      sWave: { amplitude: 0.1, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.18, width: 0.05, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 114, diastolicBP: 74, spo2: 97, etco2: 32, respiratoryRate: 17, temperature: 36.8 },
  },

  // === VENTRICULAR ===
  [CardiacRhythm.IDIOVENTRICULAR]: {
    id: CardiacRhythm.IDIOVENTRICULAR,
    name: "Idioventricular Rhythm",
    nameEs: "Ritmo Idioventricular",
    category: "ventricular",
    defaultHR: 34,
    hrRange: [20, 40],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 160,
      qWave: { amplitude: 0.1, width: 0.02 },
      rWave: { amplitude: 0.6, width: 0.03 },
      sWave: { amplitude: 0.2, width: 0.025 },
      stSegment: { elevation: 0.05 },
      tWave: { amplitude: 0.3, width: 0.08, inverted: true },
      irregularity: 0.1,
      baselineWander: 0.015,
    },
    physiologicalDefaults: { systolicBP: 81, diastolicBP: 51, spo2: 91, etco2: 24, respiratoryRate: 11, temperature: 36.1 },
  },

  [CardiacRhythm.ACCELERATED_IDIOVENTRICULAR]: {
    id: CardiacRhythm.ACCELERATED_IDIOVENTRICULAR,
    name: "Accelerated Idioventricular Rhythm",
    nameEs: "Ritmo Idioventricular Acelerado",
    category: "ventricular",
    defaultHR: 74,
    hrRange: [40, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 140,
      qWave: { amplitude: 0.1, width: 0.018 },
      rWave: { amplitude: 0.65, width: 0.028 },
      sWave: { amplitude: 0.18, width: 0.02 },
      stSegment: { elevation: 0.03 },
      tWave: { amplitude: 0.25, width: 0.07, inverted: true },
      irregularity: 0.05,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 101, diastolicBP: 66, spo2: 95, etco2: 31, respiratoryRate: 13, temperature: 36.4 },
  },

  [CardiacRhythm.VENTRICULAR_TACHYCARDIA]: {
    id: CardiacRhythm.VENTRICULAR_TACHYCARDIA,
    name: "Ventricular Tachycardia",
    nameEs: "Taquicardia Ventricular",
    category: "ventricular",
    defaultHR: 179,
    hrRange: [120, 250],
    hasPulse: false,
    isShockable: true,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 160,
      qWave: { amplitude: 0.05, width: 0.02 },
      rWave: { amplitude: 0.8, width: 0.035 },
      sWave: { amplitude: 0.3, width: 0.025 },
      stSegment: { elevation: 0.1 },
      tWave: { amplitude: 0.35, width: 0.08, inverted: true },
      irregularity: 0.05,
      baselineWander: 0.02,
    },
    physiologicalDefaults: { systolicBP: 61, diastolicBP: 41, spo2: 81, etco2: 16, respiratoryRate: 0, temperature: 36.1 },
  },

  [CardiacRhythm.POLYMORPHIC_VT]: {
    id: CardiacRhythm.POLYMORPHIC_VT,
    name: "Polymorphic VT",
    nameEs: "TV Polimórfica",
    category: "ventricular",
    defaultHR: 199,
    hrRange: [150, 300],
    hasPulse: false,
    isShockable: true,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 160,
      qWave: { amplitude: 0, width: 0 },
      rWave: { amplitude: 0.7, width: 0.03 },
      sWave: { amplitude: 0.2, width: 0.02 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.3, width: 0.06, inverted: false },
      irregularity: 0.5,
      baselineWander: 0.03,
    },
    physiologicalDefaults: { systolicBP: 0, diastolicBP: 0, spo2: 69, etco2: 9, respiratoryRate: 0, temperature: 35.9 },
  },

  [CardiacRhythm.VENTRICULAR_FIBRILLATION]: {
    id: CardiacRhythm.VENTRICULAR_FIBRILLATION,
    name: "Ventricular Fibrillation",
    nameEs: "Fibrilación Ventricular",
    category: "ventricular",
    defaultHR: 0,
    hrRange: [0, 0],
    hasPulse: false,
    isShockable: true,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 0,
      qWave: { amplitude: 0, width: 0 },
      rWave: { amplitude: 0, width: 0 },
      sWave: { amplitude: 0, width: 0 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0, width: 0, inverted: false },
      irregularity: 1,
      baselineWander: 0,
    },
    physiologicalDefaults: { systolicBP: 0, diastolicBP: 0, spo2: 0, etco2: 4, respiratoryRate: 0, temperature: 36.1 },
  },

  [CardiacRhythm.TORSADES_DE_POINTES]: {
    id: CardiacRhythm.TORSADES_DE_POINTES,
    name: "Torsades de Pointes",
    nameEs: "Torsades de Pointes",
    category: "ventricular",
    defaultHR: 199,
    hrRange: [150, 300],
    hasPulse: false,
    isShockable: true,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 0,
      qWave: { amplitude: 0, width: 0 },
      rWave: { amplitude: 0, width: 0 },
      sWave: { amplitude: 0, width: 0 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0, width: 0, inverted: false },
      irregularity: 1,
      baselineWander: 0,
    },
    physiologicalDefaults: { systolicBP: 0, diastolicBP: 0, spo2: 0, etco2: 4, respiratoryRate: 0, temperature: 35.9 },
  },

  [CardiacRhythm.AGONAL_RHYTHM]: {
    id: CardiacRhythm.AGONAL_RHYTHM,
    name: "Agonal Rhythm",
    nameEs: "Ritmo Agonal",
    category: "ventricular",
    defaultHR: 21,
    hrRange: [5, 30],
    hasPulse: false,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 200,
      qWave: { amplitude: 0.05, width: 0.03 },
      rWave: { amplitude: 0.4, width: 0.04 },
      sWave: { amplitude: 0.2, width: 0.03 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.1, inverted: true },
      irregularity: 0.5,
      baselineWander: 0.02,
    },
    physiologicalDefaults: { systolicBP: 0, diastolicBP: 0, spo2: 0, etco2: 6, respiratoryRate: 0, temperature: 35.4 },
  },

  [CardiacRhythm.ASYSTOLE]: {
    id: CardiacRhythm.ASYSTOLE,
    name: "Asystole",
    nameEs: "Asistolia",
    category: "ventricular",
    defaultHR: 0,
    hrRange: [0, 0],
    hasPulse: false,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 0,
      qWave: { amplitude: 0, width: 0 },
      rWave: { amplitude: 0, width: 0 },
      sWave: { amplitude: 0, width: 0 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0, width: 0, inverted: false },
      irregularity: 0,
      baselineWander: 0.005,
    },
    physiologicalDefaults: { systolicBP: 0, diastolicBP: 0, spo2: 0, etco2: 4, respiratoryRate: 0, temperature: 34.9 },
  },

  // === ST CHANGES ===
  [CardiacRhythm.SINUS_ST_ELEVATION]: {
    id: CardiacRhythm.SINUS_ST_ELEVATION,
    name: "Sinus with ST Elevation",
    nameEs: "Sinusal con Elevación ST",
    category: "st_changes",
    defaultHR: 79,
    hrRange: [60, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.12, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.08, width: 0.012 },
      stSegment: { elevation: 0.25 },
      tWave: { amplitude: 0.3, width: 0.07, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 129, diastolicBP: 86, spo2: 97, etco2: 35, respiratoryRate: 17, temperature: 36.5 },
  },

  [CardiacRhythm.SINUS_TACHY_ST_ELEVATION]: {
    id: CardiacRhythm.SINUS_TACHY_ST_ELEVATION,
    name: "Sinus Tachy with ST Elevation",
    nameEs: "Taquicardia Sinusal con Elevación ST",
    category: "st_changes",
    defaultHR: 114,
    hrRange: [100, 150],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.12, width: 0.03, present: true },
      prInterval: 140,
      qrsWidth: 80,
      qWave: { amplitude: 0.12, width: 0.012 },
      rWave: { amplitude: 0.75, width: 0.016 },
      sWave: { amplitude: 0.08, width: 0.011 },
      stSegment: { elevation: 0.25 },
      tWave: { amplitude: 0.28, width: 0.06, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 141, diastolicBP: 91, spo2: 96, etco2: 31, respiratoryRate: 21, temperature: 37.1 },
  },

  [CardiacRhythm.SINUS_ST_DEPRESSION]: {
    id: CardiacRhythm.SINUS_ST_DEPRESSION,
    name: "Sinus with ST Depression",
    nameEs: "Sinusal con Depresión ST",
    category: "st_changes",
    defaultHR: 84,
    hrRange: [60, 110],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: -0.2 },
      tWave: { amplitude: 0.15, width: 0.06, inverted: true },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 134, diastolicBP: 89, spo2: 95, etco2: 34, respiratoryRate: 19, temperature: 36.5 },
  },

  // === EXTRASYSTOLES ===
  [CardiacRhythm.SINUS_WITH_PVCS]: {
    id: CardiacRhythm.SINUS_WITH_PVCS,
    name: "Sinus with PVCs",
    nameEs: "Sinusal con Extrasístoles Ventriculares",
    category: "extrasystoles",
    defaultHR: 74,
    hrRange: [60, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0.15,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 117, diastolicBP: 79, spo2: 96, etco2: 34, respiratoryRate: 17, temperature: 36.6 },
  },

  [CardiacRhythm.SINUS_WITH_PACS]: {
    id: CardiacRhythm.SINUS_WITH_PACS,
    name: "Sinus with PACs",
    nameEs: "Sinusal con Extrasístoles Auriculares",
    category: "extrasystoles",
    defaultHR: 76,
    hrRange: [60, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0.1,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 121, diastolicBP: 79, spo2: 97, etco2: 36, respiratoryRate: 15, temperature: 36.4 },
  },

  [CardiacRhythm.BIGEMINY]: {
    id: CardiacRhythm.BIGEMINY,
    name: "Ventricular Bigeminy",
    nameEs: "Bigeminismo Ventricular",
    category: "extrasystoles",
    defaultHR: 79,
    hrRange: [60, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 109, diastolicBP: 73, spo2: 95, etco2: 35, respiratoryRate: 15, temperature: 36.4 },
  },

  [CardiacRhythm.TRIGEMINY]: {
    id: CardiacRhythm.TRIGEMINY,
    name: "Ventricular Trigeminy",
    nameEs: "Trigeminismo Ventricular",
    category: "extrasystoles",
    defaultHR: 81,
    hrRange: [60, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 113, diastolicBP: 75, spo2: 95, etco2: 35, respiratoryRate: 17, temperature: 36.4 },
  },

  [CardiacRhythm.COUPLET_PVCS]: {
    id: CardiacRhythm.COUPLET_PVCS,
    name: "Couplet PVCs",
    nameEs: "PVCs en Duplas",
    category: "extrasystoles",
    defaultHR: 79,
    hrRange: [60, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0.15,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 114, diastolicBP: 76, spo2: 96, etco2: 34, respiratoryRate: 17, temperature: 36.6 },
  },

  // === PREEXCITATION ===
  [CardiacRhythm.WPW]: {
    id: CardiacRhythm.WPW,
    name: "Wolff-Parkinson-White",
    nameEs: "Wolff-Parkinson-White",
    category: "preexcitation",
    defaultHR: 84,
    hrRange: [60, 200],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 100,
      qrsWidth: 120,
      qWave: { amplitude: 0.05, width: 0.025 },
      rWave: { amplitude: 0.85, width: 0.025 },
      sWave: { amplitude: 0.1, width: 0.015 },
      stSegment: { elevation: -0.05 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: true },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 119, diastolicBP: 79, spo2: 99, etco2: 36, respiratoryRate: 15, temperature: 36.6 },
  },

  [CardiacRhythm.BRUGADA_TYPE1]: {
    id: CardiacRhythm.BRUGADA_TYPE1,
    name: "Brugada Type 1",
    nameEs: "Patrón Brugada Tipo 1",
    category: "preexcitation",
    defaultHR: 71,
    hrRange: [55, 100],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 160,
      qrsWidth: 110,
      qWave: { amplitude: 0.06, width: 0.012 },
      rWave: { amplitude: 0.75, width: 0.02 },
      sWave: { amplitude: 0.1, width: 0.015 },
      stSegment: { elevation: 0.3 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: true },
      irregularity: 0,
      baselineWander: 0.01,
    },
    physiologicalDefaults: { systolicBP: 121, diastolicBP: 79, spo2: 99, etco2: 34, respiratoryRate: 15, temperature: 36.6 },
  },

  // === PACED ===
  [CardiacRhythm.PACED_ATRIAL]: {
    id: CardiacRhythm.PACED_ATRIAL,
    name: "Atrial Paced",
    nameEs: "Marcapasos Auricular",
    category: "paced",
    defaultHR: 69,
    hrRange: [40, 180],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.15, width: 0.035, present: true },
      prInterval: 180,
      qrsWidth: 80,
      qWave: { amplitude: 0.08, width: 0.012 },
      rWave: { amplitude: 0.8, width: 0.018 },
      sWave: { amplitude: 0.12, width: 0.012 },
      stSegment: { elevation: 0 },
      tWave: { amplitude: 0.2, width: 0.06, inverted: false },
      irregularity: 0,
      baselineWander: 0.005,
    },
    physiologicalDefaults: { systolicBP: 116, diastolicBP: 76, spo2: 98, etco2: 34, respiratoryRate: 17, temperature: 36.4 },
  },

  [CardiacRhythm.PACED_VENTRICULAR]: {
    id: CardiacRhythm.PACED_VENTRICULAR,
    name: "Ventricular Paced",
    nameEs: "Marcapasos Ventricular",
    category: "paced",
    defaultHR: 69,
    hrRange: [40, 180],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0, width: 0, present: false },
      prInterval: 0,
      qrsWidth: 160,
      qWave: { amplitude: 0, width: 0 },
      rWave: { amplitude: 0.7, width: 0.03 },
      sWave: { amplitude: 0.25, width: 0.025 },
      stSegment: { elevation: -0.1 },
      tWave: { amplitude: 0.3, width: 0.08, inverted: true },
      irregularity: 0,
      baselineWander: 0.005,
    },
    physiologicalDefaults: { systolicBP: 111, diastolicBP: 71, spo2: 95, etco2: 34, respiratoryRate: 15, temperature: 36.4 },
  },

  [CardiacRhythm.PACED_AV_SEQUENTIAL]: {
    id: CardiacRhythm.PACED_AV_SEQUENTIAL,
    name: "AV Sequential Paced",
    nameEs: "Marcapasos AV Secuencial",
    category: "paced",
    defaultHR: 69,
    hrRange: [40, 180],
    hasPulse: true,
    isShockable: false,
    waveformParams: {
      pWave: { amplitude: 0.12, width: 0.03, present: true },
      prInterval: 200,
      qrsWidth: 160,
      qWave: { amplitude: 0, width: 0 },
      rWave: { amplitude: 0.7, width: 0.03 },
      sWave: { amplitude: 0.25, width: 0.025 },
      stSegment: { elevation: -0.08 },
      tWave: { amplitude: 0.28, width: 0.08, inverted: true },
      irregularity: 0,
      baselineWander: 0.005,
    },
    physiologicalDefaults: { systolicBP: 114, diastolicBP: 76, spo2: 98, etco2: 34, respiratoryRate: 17, temperature: 36.6 },
  },
};
